import { chapter, edge, hints, lesson, w } from './shared'

const lessons = [
  lesson('box-diamond', 'box-diamond-possible-not-necessary', 'Possible but not necessary', 'Construct a model where ◇p is true and □p is false.',
    { heading: 'Diamond needs one; box checks all', intuitive: 'Keep one p-successor as a witness and create one successor without p as a counterexample.', formula: '◇p / □p', keyPoints: ['◇ is existential.', '□ is universal.'] },
    { instruction: 'Make ◇p true and □p false at w0.', formula: '◇p', comparisonFormula: '□p', comparisonTarget: { formulaATruth: true, formulaBTruth: false }, scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 60), w('w1', 'p', 360, 60), w('w2', 'p', 360, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2')], constraints: { maximumChanges: 1 }, editable: ['valuations'] },
    hints('◇p needs at least one p-successor.', '□p fails if another successor lacks p.', 'Remove p from exactly one of w1 and w2.'), 'One branch witnesses possibility while the other refutes necessity.'),

  lesson('box-diamond', 'box-diamond-neither', 'Neither possible nor necessary', 'Make both ◇p and □p false.',
    { heading: 'No p-successor defeats both claims', intuitive: 'Diamond loses its witness and box still has a counterexample.', formula: '◇p / □p', keyPoints: ['Remove the only p.', 'Keep both successors.'] },
    { instruction: 'Make ◇p false and □p false at w0.', formula: '◇p', comparisonFormula: '□p', comparisonTarget: { formulaATruth: false, formulaBTruth: false }, scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: [w('w0', '', 60), w('w1', 'p', 360, 60), w('w2', '', 360, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2')], constraints: { maximumChanges: 1 }, editable: ['valuations'] },
    hints('◇p currently has one witness.', 'Remove that witness without adding any new one.', 'Remove p from w1.'), 'No successor has p, so possibility fails; the successors also refute necessity.'),

  lesson('box-diamond', 'box-diamond-both', 'Possible and necessary', 'Use accessibility to make ◇p and □p true together.',
    { heading: 'All accessible worlds can be witnesses', intuitive: 'Keep only the p-successor accessible.', formula: '◇p / □p', keyPoints: ['A nonempty all-p successor set satisfies both.', 'Remove the bad branch.'] },
    { instruction: 'Make ◇p and □p true at w0 using exactly one edge.', formula: '◇p', comparisonFormula: '□p', comparisonTarget: { formulaATruth: true, formulaBTruth: true }, scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 60), w('w1', 'p', 360, 60), w('w2', '', 360, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2')], constraints: { minimumEdges: 1, maximumEdges: 1, requiredEdges: [edge('w0', 'w1')], forbiddenEdges: [edge('w0', 'w2')] }, editable: ['edges'] },
    hints('w1 witnesses ◇p.', 'w2 is the only counterexample to □p.', 'Remove w0 → w2 and keep w0 → w1.'), 'The remaining successor has p, so it witnesses ◇p and all successors satisfy □p.'),

  lesson('box-diamond', 'box-diamond-necessary-not-possible', 'Necessary but not possible', 'Use vacuous truth to separate □p from ◇p.',
    { heading: 'A dead end separates box from diamond', intuitive: 'With no successors, □p is vacuously true but ◇p has no witness.', formula: '□p / ◇p', keyPoints: ['Remove the only edge.', 'The valuation may stay fixed.'] },
    { instruction: 'Make □p true and ◇p false at w0.', formula: '□p', comparisonFormula: '◇p', comparisonTarget: { formulaATruth: true, formulaBTruth: false }, scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 100), w('w1', 'p', 390)], edges: [edge('w0', 'w1')], constraints: { minimumEdges: 0, maximumEdges: 0 }, editable: ['edges'] },
    hints('◇p needs an accessible witness.', '□p permits an empty successor set.', 'Remove w0 → w1.'), 'At the resulting dead end, □p is vacuously true and ◇p is false.'),

  lesson('box-diamond', 'box-diamond-diamond-duality', 'Diamond duality', 'Verify ◇p ↔ ¬□¬p on a finite frame.',
    { heading: 'Possibility is not-necessary-not', intuitive: 'An accessible p-witness exists exactly when not every successor falsifies p.', formal: '◇p ↔ ¬□¬p', formula: '(◇p → ¬□¬p) ∧ (¬□¬p → ◇p)', keyPoints: ['Both directions are valid.', 'The claim includes dead ends.'] },
    { interactionMode: 'question', briefing: 'The model is read-only. Valid on this frame means true at every world under every valuation on this fixed relation.', instruction: 'Determine whether ◇p ↔ ¬□¬p is valid on the displayed frame.', formula: '(◇p → ¬□¬p) ∧ (¬□¬p → ◇p)', scope: 'frame', targetTruth: true, evaluationWorld: 'w0', prediction: { kind: 'truth', prompt: 'Is ◇p ↔ ¬□¬p valid on this frame?', mustBeCorrect: true }, worlds: [w('w0', '', 50), w('w1', '', 300, 50), w('w2', '', 300, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2'), edge('w1', 'w1')], editable: [] },
    hints('Read ¬□¬p as “not every successor lacks p.”', 'That is equivalent to having at least one p-successor.', 'Choose Valid on this frame.'), 'The finite check confirms the equivalence at every world under every valuation on this displayed frame. The duality is a general valid principle, but one finite instance is not by itself a proof of that general fact.'),

  lesson('box-diamond', 'box-diamond-box-duality', 'Box duality', 'Verify □p ↔ ¬◇¬p on a finite frame.',
    { heading: 'Necessity is not-possible-not', intuitive: 'Every accessible world has p exactly when no accessible world has ¬p.', formal: '□p ↔ ¬◇¬p', formula: '(□p → ¬◇¬p) ∧ (¬◇¬p → □p)', keyPoints: ['The equivalence is valuation-independent.', 'Dead ends satisfy both sides.'] },
    { interactionMode: 'question', briefing: 'The model is read-only. Valid on this frame means true at every world under every valuation on this fixed relation.', instruction: 'Determine whether □p ↔ ¬◇¬p is valid on the displayed frame.', formula: '(□p → ¬◇¬p) ∧ (¬◇¬p → □p)', scope: 'frame', targetTruth: true, evaluationWorld: 'w0', prediction: { kind: 'truth', prompt: 'Is □p ↔ ¬◇¬p valid on this frame?', mustBeCorrect: true }, worlds: [w('w0', '', 40), w('w1', '', 270), w('w2', '', 500)], edges: [edge('w0', 'w1'), edge('w1', 'w2'), edge('w2', 'w2')], editable: [] },
    hints('A counterexample to □p would be a successor satisfying ¬p.', '¬◇¬p says that no such successor exists.', 'Choose Valid on this frame.'), 'The finite check confirms the equivalence at every world under every valuation on this displayed frame. The duality is a general valid principle, but one finite instance is not by itself a proof of that general fact.'),
]

export const boxDiamondChapter = chapter('box-diamond', 'Box and Diamond', 'Compare existential and universal modal truth and verify their dualities.', ['necessity'], lessons, ['◇p needs at least one p-successor, while □p requires every successor to satisfy p.', 'The two operators can have four different truth profiles.', '◇φ is equivalent to ¬□¬φ, and □φ is equivalent to ¬◇¬φ.'], 'Continue to Nested Modalities to evaluate formulas across more than one modal step.')
