import { chapter, edge, hints, lesson, w } from './shared'

const lessons = [
  lesson('necessity', 'necessity-one-successor', 'One successor', 'Make □p true by repairing its only accessible successor.',
    { heading: 'Necessity checks every successor', intuitive: 'With one outgoing edge, the one target must satisfy p.', formal: 'M,w ⊨ □p iff every v with wRv satisfies p.', formula: '□p', keyPoints: ['Follow edges out of the evaluation world.', 'Every target is checked.'] },
    { instruction: 'Make □p true at w0.', formula: '□p', scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 90), w('w1', '', 390)], edges: [edge('w0', 'w1')], constraints: { minimumWorlds: 2, maximumWorlds: 2, minimumEdges: 1, maximumEdges: 1 }, editable: ['valuations'] },
    hints('Inspect the only arrow leaving w0.', 'Its target w1 does not yet satisfy p.', 'Add p to w1.'), 'The only accessible successor now satisfies p.'),

  lesson('necessity', 'necessity-every-successor', 'Every successor', 'See that every accessible branch must satisfy the boxed formula.',
    { heading: 'One counterexample defeats a box', intuitive: 'A single accessible successor without p makes □p false.', formal: 'All outgoing targets, not merely one, must satisfy p.', formula: '□p', keyPoints: ['w1 already has p.', 'w2 is also accessible.'] },
    { instruction: 'Make □p true at w0 without changing the relation.', formula: '□p', scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 60), w('w1', 'p', 360, 60), w('w2', '', 360, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2')], constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredAtoms: { w1: ['p'] } }, editable: ['valuations'] },
    hints('Check both successors of w0.', 'w1 passes, but w2 is a counterexample.', 'Add p to w2.'), 'Both accessible successors satisfy p.', { diagnosticFeedback: { 'box-counterexample': 'At least one accessible successor still falsifies p. every successor must pass.' } }),

  lesson('necessity', 'necessity-counterexample', 'Find the counterexample', 'Identify the successor that falsifies a necessity claim.',
    { heading: 'A failing successor is a box counterexample', intuitive: 'To explain why □p is false, point to an accessible world where p fails.', formula: '□p', keyPoints: ['Only successors of w0 matter.', 'Look for the one without p.'] },
    { interactionMode: 'question', instruction: 'Choose the accessible counterexample to □p at w0.', formula: '□p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', prediction: { kind: 'world-choice', prompt: 'Which successor makes □p false?', expectedChoice: 'w2', worldChoices: ['w1', 'w2', 'w3'], mustBeCorrect: true }, worlds: [w('w0', '', 40), w('w1', 'p', 340, 30), w('w2', '', 340, 130), w('w3', 'p', 340, 230)], edges: [edge('w0', 'w1'), edge('w0', 'w2'), edge('w0', 'w3')], editable: [] },
    hints('Inspect every target of an edge from w0.', 'A counterexample must lack p.', 'Choose w2.'), 'w2 is accessible and lacks p, so it refutes □p at w0.'),

  lesson('necessity', 'necessity-inaccessible', 'Inaccessible worlds do not matter', 'Separate accessible counterexamples from irrelevant worlds.',
    { heading: 'Box ranges only over accessible worlds', intuitive: 'A world without p is irrelevant if no edge from w0 reaches it.', formula: '□p', keyPoints: ['w1 is accessible.', 'w2 is not accessible.'] },
    { instruction: 'Make □p false at w0 with one valuation change.', formula: '□p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: [w('w0', '', 60), w('w1', 'p', 350, 70), w('w2', '', 350, 210)], edges: [edge('w0', 'w1')], constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 1, maximumEdges: 1, maximumChanges: 1 }, editable: ['valuations'] },
    hints('Changing the inaccessible w2 cannot affect □p at w0.', 'The only checked world is w1.', 'Remove p from w1.'), 'The accessible world w1 now refutes □p. the inaccessible w2 never mattered.', { diagnosticFeedback: { 'formula-false': 'An inaccessible world cannot determine □p at w0. change the valuation of an accessible successor.' } }),

  lesson('necessity', 'necessity-vacuous', 'Vacuous necessity', 'Recognize why necessity is true at a dead end.',
    { heading: 'No successors means no counterexample', intuitive: 'At a world with no outgoing edges, every successor satisfies p because there are none.', formal: 'A universal condition over an empty successor set is true.', formula: '□p', keyPoints: ['w0 has no successors.', 'No p-world is required.'], warning: 'Vacuous truth does not assert p at w0.' },
    { interactionMode: 'question', instruction: 'Determine whether □p is true at the dead end w0.', formula: '□p', scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', prediction: { kind: 'truth', prompt: 'Is □p true at w0 when w0 has no successors?', mustBeCorrect: true }, worlds: [w('w0')], edges: [], editable: [] },
    hints('Count the successors of w0.', 'There is no successor that can falsify p.', 'Choose True: □p holds vacuously.'), '□p is vacuously true because w0 has no accessible counterexample.', { transferTask: { id: 'learn-necessity-vacuous-transfer', chapter: 'Necessity', title: 'End vacuous truth', concept: 'Add a counterexample successor', learningObjective: 'Make a vacuously true necessity false by adding one edge.', instruction: 'Make □p false at w0 by adding exactly one edge.', formula: '□p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: [w('w0', '', 100), w('w1', '', 390)], edges: [], constraints: { minimumWorlds: 2, maximumWorlds: 2, minimumEdges: 1, maximumEdges: 1, requiredEdges: [edge('w0', 'w1')] }, editable: ['edges'] } }),

  lesson('necessity', 'necessity-repair', 'Repair necessity', 'Repair □p using one semantic change.',
    { heading: 'A box can be repaired in several ways', intuitive: 'Fix the bad valuation, remove its incoming accessibility, or evaluate at a world where the box already holds.', formula: '□p', keyPoints: ['w1 is the only bad successor of w0.', 'The change budget is one.'] },
    { instruction: 'Make □p true at w0 using at most one change.', formula: '□p', scope: 'pointed', targetTruth: true, evaluationWorld: 'w0', worlds: [w('w0', '', 50), w('w1', '', 300, 50), w('w2', 'p', 300, 210)], edges: [edge('w0', 'w1'), edge('w0', 'w2'), edge('w1', 'w1'), edge('w2', 'w2')], constraints: { minimumWorlds: 3, maximumWorlds: 3, maximumChanges: 1 }, editable: ['valuations', 'edges', 'evaluation'], workspacePresentation: { valuations: true, edges: true, evaluation: true, visibleConstraints: ['Use at most one semantic change.'] } },
    hints('Find the only bad successor of w0.', 'You may change a valuation, an edge, or the evaluation world.', 'Add p to w1, remove w0 → w1, or evaluate at w2.'), 'One targeted change removes the only counterexample to necessity.'),
]

export const necessityChapter = chapter('necessity', 'Necessity', 'Understand universal modal truth and counterexample successors.', ['possibility'], lessons, ['□φ is true when every accessible successor satisfies φ.', 'One accessible counterexample is enough to make □φ false.', 'Inaccessible worlds do not matter, and worlds without successors make □φ vacuously true.'], 'Continue to Box and Diamond to compare their possible truth profiles and dualities.')
